# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: check-format
        name: Check Code Format
        description: Check code formatting using autopep8, isort, and black.
        entry: make check-format
        language: system
        always_run: true
    -   id: lint
        name: Lint Code
        description: Run flake8 and mypy for code linting.
        entry: make lint
        language: system
        always_run: true
